// Minimal XLSX writer for Cloudflare Workers: no Node dependencies required.
const enc=new TextEncoder();
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function col(n){let s="";for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;}
function sheet(rows){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows.map((r,ri)=>`<row r="${ri+1}">${r.map((v,ci)=>{const ref=`${col(ci)}${ri+1}`;return typeof v==="number"&&Number.isFinite(v)?`<c r="${ref}"><v>${v}</v></c>`:`<c r="${ref}" t="inlineStr"><is><t>${esc(v)}</t></is></c>`;}).join("")}</row>`).join("")}</sheetData></worksheet>`;}
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function u16(n){return new Uint8Array([n&255,(n>>>8)&255]);} function u32(n){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]);} function cat(parts){const len=parts.reduce((s,p)=>s+p.length,0),out=new Uint8Array(len);let o=0;for(const p of parts){out.set(p,o);o+=p.length;}return out;}
function zip(files){const local=[],central=[];let offset=0;for(const [name,text] of files){const n=enc.encode(name),d=enc.encode(text),crc=crc32(d),lh=cat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(d.length),u32(d.length),u16(n.length),u16(0),n,d]);local.push(lh);central.push(cat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(d.length),u32(d.length),u16(n.length),u16(0),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),n]));offset+=lh.length;}const cd=cat(central),body=cat(local);return cat([body,cd,u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(cd.length),u32(body.length),u16(0)]);}
function uaDate(v){const m=String(v||"").match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}.${m[2]}.${m[1]}`:String(v||"");}
function statusLabel(key){const labels={new:"Нові",agreed:"Погодження / в роботі",work:"Погодження / в роботі",production:"Виробництво",delivery:"В доставці",received:"Отримано / виконано",delivered:"Отримано / виконано",completed:"Отримано / виконано",cancelled:"Скасовано / відмови",canceled:"Скасовано / відмови"};return labels[key]||key;}
export function buildXlsx(data,rows){const activeStatusRows=Object.entries(data.statusMetrics||{}).filter(([key])=>(data.statusSettings?.[key]||[]).length>0).map(([key,m])=>[statusLabel(key),m?.count||0,m?.sum||0]);const summary=[["Показник","Кількість","Сума, UAH"],["Період",`${uaDate(data.range.from)} — ${uaDate(data.range.to)}`,""],["Замовлень",data.kpiOrders.length,data.total],["Оплачено","",data.paid],["Повністю оплачено",data.fullyPaid.length,""],["Частково оплачено",data.partialPaidOrders.length,""],["Не оплачено",data.unpaidOrders.length,""],...activeStatusRows,["Середній чек","",data.average],["Валюта",data.currency,""]];const orders=[["Дата","№ замовлення","Джерело","Менеджер","Статус","Сума","Оплачено","Стан оплати"],...rows.map(r=>[r.date,r.number,r.source,r.manager,r.status,r.total,r.paid,r.payment])];return zip([["[Content_Types].xml",`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`],["_rels/.rels",`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`],["xl/workbook.xml",`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Підсумок" sheetId="1" r:id="rId1"/><sheet name="Замовлення" sheetId="2" r:id="rId2"/></sheets></workbook>`],["xl/_rels/workbook.xml.rels",`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/></Relationships>`],["xl/worksheets/sheet1.xml",sheet(summary)],["xl/worksheets/sheet2.xml",sheet(orders)]]);}
