import { buildOrdersReport, getReportData, exportRows } from "./reports.js";
import { buildXlsx } from "./excel.js";
import { syncOrderState } from "./order-state.js";
import { answerCallback, mainKeyboard, reportKeyboard, sendMessage, sendDocument, settingsHomeKeyboard, statusSettingsKeyboard, statusGroupKeyboard, paymentSettingsKeyboard, connectKeyboard, crmInfoKeyboard } from "./telegram.js";
import { getStatusSettings, loadStatuses, settingsSummary, toggleStatus, STATUS_LABELS, getPaymentSettings, togglePaymentSetting, paymentSettingsSummary } from "./settings.js";
import { getClient, saveClient, disconnectClient, envForClient } from "./clients.js";
import { validateKeycrmToken } from "./keycrm.js";

const pendingTokenUsers = new Map();
const TOKEN_WAIT_MS = 10 * 60 * 1000;
function startTokenOnboarding(userId){pendingTokenUsers.set(String(userId),Date.now()+TOKEN_WAIT_MS);}
function stopTokenOnboarding(userId){pendingTokenUsers.delete(String(userId));}
function isWaitingForToken(userId){const key=String(userId),expires=pendingTokenUsers.get(key);if(!expires)return false;if(expires<Date.now()){pendingTokenUsers.delete(key);return false;}return true;}
function connectInstructions(){return "🔗 <b>Підключення KeyCRM</b>\n\n1. Відкрийте KeyCRM → Налаштування → Загальні → API.\n2. Скопіюйте ваш API token.\n3. Надішліть <b>лише token</b> наступним повідомленням у цей чат.\n\n🔒 Повідомлення з token буде автоматично видалено після отримання.\n⏱ Очікую token протягом 10 хвилин.";}
function validWebhook(request,env){if(!env.WEBHOOK_SECRET)return true;return request.headers.get("X-Telegram-Bot-Api-Secret-Token")===env.WEBHOOK_SECRET;}
async function telegramApi(env,method,body={}){if(!env.TELEGRAM_BOT_TOKEN)throw new Error("TELEGRAM_BOT_TOKEN is not configured");const response=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.description||`Telegram API error (${response.status})`);return data;}
const BOT_COMMANDS=[{command:"start",description:"Відкрити головне меню"},{command:"connect",description:"Підключити KeyCRM"},{command:"disconnect",description:"Відключити KeyCRM"}];
async function syncBotCommands(env){await telegramApi(env,"setMyCommands",{commands:BOT_COMMANDS});}
async function setupWebhook(request,env){try{const origin=new URL(request.url).origin,webhookUrl=`${origin}/webhook`,body={url:webhookUrl,allowed_updates:["message","callback_query"],drop_pending_updates:true};if(env.WEBHOOK_SECRET)body.secret_token=env.WEBHOOK_SECRET;await telegramApi(env,"setWebhook",body);await syncBotCommands(env);const info=await telegramApi(env,"getWebhookInfo");return Response.json({ok:true,message:"Telegram webhook and commands configured",webhook_url:info.result?.url||webhookUrl,pending_update_count:info.result?.pending_update_count??0,last_error_message:info.result?.last_error_message||null,secret_token_enabled:Boolean(env.WEBHOOK_SECRET),commands:BOT_COMMANDS});}catch(error){return Response.json({ok:false,error:error.message},{status:500});}}
async function clientContext(env,userId){const client=await getClient(env,userId);return client?{client,clientEnv:envForClient(env,client)}:null;}
async function saveValidatedClient(env,message,userId,chatId,token){try{await telegramApi(env,"deleteMessage",{chat_id:chatId,message_id:message.message_id});}catch(error){console.error("Failed to delete message containing KeyCRM token",error);}try{await validateKeycrmToken(token);await saveClient(env,{telegramUserId:userId,telegramChatId:chatId,telegramUsername:message.from?.username,displayName:[message.from?.first_name,message.from?.last_name].filter(Boolean).join(" "),keycrmToken:token});stopTokenOnboarding(userId);return sendMessage(env,chatId,"✅ <b>KeyCRM успішно підключено.</b>\n\nТепер можна формувати звіти.",mainKeyboard());}catch(error){console.error("KeyCRM connect failed",error);startTokenOnboarding(userId);return sendMessage(env,chatId,"❌ Не вдалося підключити KeyCRM. Перевірте API token і надішліть його ще раз.");}}
async function buildSyncedReport(env,period,chatId){try{await syncOrderState(env);}catch(error){console.error("Order state sync failed",error);}return buildOrdersReport(env,period,chatId);}
async function showStatusSettings(env,chatId){const [groups,statuses]=await Promise.all([getStatusSettings(env,chatId),loadStatuses(env)]);return sendMessage(env,chatId,settingsSummary(groups,statuses),statusSettingsKeyboard(groups));}
async function showStatusGroup(env,chatId,groupKey){const [groups,statuses]=await Promise.all([getStatusSettings(env,chatId),loadStatuses(env)]);return sendMessage(env,chatId,`⚙️ <b>${STATUS_LABELS[groupKey]||groupKey}</b>\n\nНатисніть на статус, щоб додати або прибрати його з цієї групи.`,statusGroupKeyboard(groupKey,statuses,groups[groupKey]||[]));}
async function showPaymentSettings(env,chatId){const settings=await getPaymentSettings(env,chatId);return sendMessage(env,chatId,paymentSettingsSummary(settings),paymentSettingsKeyboard(settings));}
function parseInputDate(s){const v=String(s||"").trim();let m=v.match(/^(\d{2})[.\/-](\d{2})[.\/-](\d{4})$/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;m=v.match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?v:null;}
function formatUaDate(v){const m=String(v||"").match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}.${m[2]}.${m[1]}`:String(v||"");}
function parseCustomRange(text){const matches=String(text||"").match(/\d{2}[.\/-]\d{2}[.\/-]\d{4}|\d{4}-\d{2}-\d{2}/g)||[];if(matches.length<2)return null;const from=parseInputDate(matches[0]),to=parseInputDate(matches[1]);return from&&to?{from,to}:null;}
function periodKey(period){return typeof period==="object"?`custom:${period.from}:${period.to}`:period;}
function decodePeriodKey(key){if(key.startsWith("custom:")){const [,from,to]=key.split(":");return {from,to};}return key;}
async function sendReport(env,chatId,period){const report=await buildSyncedReport(env,period,chatId);return sendMessage(env,chatId,report,reportKeyboard(periodKey(period)));}
async function sendExcel(env,chatId,period){try{await syncOrderState(env);}catch(e){console.error(e);}const data=await getReportData(env,period,chatId),bytes=buildXlsx(data,exportRows(data)),from=formatUaDate(data.range.from),to=formatUaDate(data.range.to),filename=`CRM-звіт_${from}-${to}.xlsx`;return sendDocument(env,chatId,bytes,filename,`📊 Звіт ${from} — ${to}`);}
async function handleUpdate(update,env){
 if(update.message){const message=update.message,chatId=message.chat.id,userId=message.from?.id??chatId,text=(message.text||"").trim(),ctx=await clientContext(env,userId);
  if(text==="/start"){stopTokenOnboarding(userId);if(!ctx)return sendMessage(env,chatId,"👋 <b>CRM Report Bot</b>\n\nЩоб отримувати звіти, спочатку підключіть вашу KeyCRM.",connectKeyboard());return sendMessage(env,chatId,`👋 <b>${env.COMPANY_NAME||"KeyCRM"} Telegram Assistant</b>\n\nОберіть звіт:`,mainKeyboard());}
  if(text==="/connect"){startTokenOnboarding(userId);return sendMessage(env,chatId,connectInstructions());}
  if(text.startsWith("/connect ")){const token=text.slice(9).trim();if(!token)return sendMessage(env,chatId,"Надішліть API token наступним повідомленням.");return saveValidatedClient(env,message,userId,chatId,token);}
  if(text==="/disconnect"){stopTokenOnboarding(userId);if(ctx)await disconnectClient(env,userId);return sendMessage(env,chatId,"🔌 KeyCRM відключено. Звіти недоступні, доки ви не підключите CRM знову.",connectKeyboard());}
  if(!ctx&&isWaitingForToken(userId)&&text&&!text.startsWith("/"))return saveValidatedClient(env,message,userId,chatId,text);
  if(!ctx)return sendMessage(env,chatId,"🔗 Спочатку підключіть KeyCRM.",connectKeyboard());
  const clientEnv=ctx.clientEnv;
  if(text==="/report")try{return await sendReport(clientEnv,chatId,"yesterday");}catch(error){return sendMessage(env,chatId,`⚠️ Помилка формування звіту: ${error.message}`,mainKeyboard());}
  const custom=parseCustomRange(text);if(custom)try{return await sendReport(clientEnv,chatId,custom);}catch(error){return sendMessage(env,chatId,`⚠️ ${error.message}\n\nВведіть період ще раз, наприклад: <code>01.09.2026 - 30.09.2026</code>`,mainKeyboard());}
  return sendMessage(env,chatId,"Натисніть /start, щоб відкрити меню.",mainKeyboard());
 }
 if(update.callback_query){const callback=update.callback_query,chatId=callback.message?.chat?.id,userId=callback.from?.id??chatId,data=callback.data||"";try{await answerCallback(env,callback.id);}catch(e){}if(!chatId)return;const ctx=await clientContext(env,userId);
  if(data==="crm_connect"){startTokenOnboarding(userId);return sendMessage(env,chatId,connectInstructions());}
  if(data==="crm_info"){if(!ctx)return sendMessage(env,chatId,"KeyCRM ще не підключено.",connectKeyboard());return sendMessage(env,chatId,`🔗 <b>KeyCRM підключено</b>\n\nВалюта: <b>${ctx.client.currency||"UAH"}</b>\nЧасовий пояс: <b>${ctx.client.timezone||"Europe/Kyiv"}</b>`,crmInfoKeyboard());}
  if(data==="crm_disconnect"){stopTokenOnboarding(userId);if(ctx)await disconnectClient(env,userId);return sendMessage(env,chatId,"🔌 KeyCRM відключено. Звіти недоступні, доки ви не підключите CRM знову.",connectKeyboard());}
  if(!ctx)return sendMessage(env,chatId,"🔗 Спочатку підключіть KeyCRM.",connectKeyboard());const clientEnv=ctx.clientEnv;
  if(data==="settings_home")return sendMessage(env,chatId,"⚙️ <b>Налаштування звітів</b>\n\nОберіть, що потрібно налаштувати:",settingsHomeKeyboard());
  if(data==="settings_statuses")try{return await showStatusSettings(clientEnv,chatId);}catch(error){return sendMessage(env,chatId,`⚠️ Помилка налаштувань: ${error.message}`,mainKeyboard());}
  if(data==="settings_payments")try{return await showPaymentSettings(clientEnv,chatId);}catch(error){return sendMessage(env,chatId,`⚠️ Помилка налаштувань оплати: ${error.message}`,mainKeyboard());}
  if(data.startsWith("settings_payment_")){const key=data.slice(17);try{await togglePaymentSetting(clientEnv,chatId,key);return await showPaymentSettings(clientEnv,chatId);}catch(error){return sendMessage(env,chatId,`⚠️ Не вдалося зберегти налаштування оплати: ${error.message}`,mainKeyboard());}}
  if(data==="settings_back")return sendMessage(env,chatId,"Оберіть звіт:",mainKeyboard());
  if(data.startsWith("settings_group_")){const groupKey=data.slice(15);try{return await showStatusGroup(clientEnv,chatId,groupKey);}catch(error){return sendMessage(env,chatId,`⚠️ Помилка налаштувань: ${error.message}`,mainKeyboard());}}
  if(data.startsWith("settings_toggle_")){const rest=data.slice(16),separator=rest.indexOf("_"),groupKey=separator>=0?rest.slice(0,separator):"",statusId=separator>=0?rest.slice(separator+1):"";try{await toggleStatus(clientEnv,chatId,groupKey,statusId);return await showStatusGroup(clientEnv,chatId,groupKey);}catch(error){return sendMessage(env,chatId,`⚠️ Не вдалося зберегти статус: ${error.message}`,mainKeyboard());}}
  if(data==="orders_custom")return sendMessage(env,chatId,"📆 <b>Довільний період</b>\n\nВведіть дві дати одним повідомленням.\nНаприклад: <code>01.09.2026 - 30.09.2026</code>",mainKeyboard());
  if(data.startsWith("excel_")){try{return await sendExcel(clientEnv,chatId,decodePeriodKey(data.slice(6)));}catch(error){console.error("Excel export failed",error);return sendMessage(env,chatId,`⚠️ Помилка створення Excel: ${error.message}`,mainKeyboard());}}
  if(data.startsWith("orders_")){const period=data.slice(7);try{return await sendReport(clientEnv,chatId,period);}catch(error){return sendMessage(env,chatId,`⚠️ Помилка формування звіту (${period}): ${error.message}`,mainKeyboard());}}
  return sendMessage(env,chatId,`⚠️ Невідома команда кнопки: ${data}`,mainKeyboard());
 }}
export default {async fetch(request,env,ctx){const url=new URL(request.url);if(request.method==="GET"&&url.pathname==="/health")return Response.json({ok:true,service:"keycrm-telegram-assistant",version:"5.1.0-token-onboarding",d1:Boolean(env.DB)});if(request.method==="GET"&&url.pathname==="/setup")return setupWebhook(request,env);if(request.method!=="POST"||url.pathname!=="/webhook")return new Response("Not found",{status:404});if(!validWebhook(request,env))return new Response("Unauthorized",{status:401});try{const update=await request.json();ctx.waitUntil(handleUpdate(update,env).catch(error=>console.error("handleUpdate failed",error)));return new Response("OK");}catch(error){return new Response("Bad request",{status:400});}},async scheduled(controller,env,ctx){ctx.waitUntil(syncOrderState(env).catch(error=>console.error("Scheduled order-state sync failed",error)));}};
