import { buildOrdersReport, getReportData, exportRows } from "./reports.js";
import { buildXlsx } from "./excel.js";
import { syncOrderState } from "./order-state.js";
import { answerCallback, mainKeyboard, reportKeyboard, sendMessage, sendDocument, settingsHomeKeyboard, statusSettingsKeyboard, statusGroupKeyboard, paymentSettingsKeyboard } from "./telegram.js";
import { getStatusSettings, loadStatuses, settingsSummary, toggleStatus, STATUS_LABELS, getPaymentSettings, togglePaymentSetting, paymentSettingsSummary } from "./settings.js";
function validWebhook(request,env){if(!env.WEBHOOK_SECRET)return true;return request.headers.get("X-Telegram-Bot-Api-Secret-Token")===env.WEBHOOK_SECRET;}
async function telegramApi(env,method,body={}){if(!env.TELEGRAM_BOT_TOKEN)throw new Error("TELEGRAM_BOT_TOKEN is not configured");const response=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.description||`Telegram API error (${response.status})`);return data;}
async function setupWebhook(request,env){try{const origin=new URL(request.url).origin,webhookUrl=`${origin}/webhook`,body={url:webhookUrl,allowed_updates:["message","callback_query"],drop_pending_updates:true};if(env.WEBHOOK_SECRET)body.secret_token=env.WEBHOOK_SECRET;await telegramApi(env,"setWebhook",body);const info=await telegramApi(env,"getWebhookInfo");return Response.json({ok:true,message:"Telegram webhook configured",webhook_url:info.result?.url||webhookUrl,pending_update_count:info.result?.pending_update_count??0,last_error_message:info.result?.last_error_message||null,secret_token_enabled:Boolean(env.WEBHOOK_SECRET)});}catch(error){return Response.json({ok:false,error:error.message},{status:500});}}
async function buildSyncedReport(env,period,chatId){try{await syncOrderState(env);}catch(error){console.error("Order state sync failed",error);}return buildOrdersReport(env,period,chatId);}
async function showStatusSettings(env,chatId){const [groups,statuses]=await Promise.all([getStatusSettings(env,chatId),loadStatuses(env)]);return sendMessage(env,chatId,settingsSummary(groups,statuses),statusSettingsKeyboard(groups));}
async function showStatusGroup(env,chatId,groupKey){const [groups,statuses]=await Promise.all([getStatusSettings(env,chatId),loadStatuses(env)]);return sendMessage(env,chatId,`⚙️ <b>${STATUS_LABELS[groupKey]||groupKey}</b>\n\nНатисніть на статус, щоб додати або прибрати його з цієї групи.`,statusGroupKeyboard(groupKey,statuses,groups[groupKey]||[]));}
async function showPaymentSettings(env,chatId){const settings=await getPaymentSettings(env,chatId);return sendMessage(env,chatId,paymentSettingsSummary(settings),paymentSettingsKeyboard(settings));}
function parseInputDate(s){const v=String(s||"").trim();let m=v.match(/^(\d{2})[.\/-](\d{2})[.\/-](\d{4})$/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;m=v.match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?v:null;}
function parseCustomRange(text){const matches=String(text||"").match(/\d{2}[.\/-]\d{2}[.\/-]\d{4}|\d{4}-\d{2}-\d{2}/g)||[];if(matches.length<2)return null;const from=parseInputDate(matches[0]),to=parseInputDate(matches[1]);return from&&to?{from,to}:null;}
function periodKey(period){return typeof period==="object"?`custom:${period.from}:${period.to}`:period;}
function decodePeriodKey(key){if(key.startsWith("custom:")){const [,from,to]=key.split(":");return {from,to};}return key;}
async function sendReport(env,chatId,period){const report=await buildSyncedReport(env,period,chatId);return sendMessage(env,chatId,report,reportKeyboard(periodKey(period)));}
async function sendExcel(env,chatId,period){try{await syncOrderState(env);}catch(e){console.error(e);}const data=await getReportData(env,period,chatId),bytes=buildXlsx(data,exportRows(data)),filename=`keycrm-report-${data.range.from}-${data.range.to}.xlsx`;return sendDocument(env,chatId,bytes,filename,`📊 Звіт ${data.range.from} — ${data.range.to}`);}
async function handleUpdate(update,env){if(update.message){const chatId=update.message.chat.id,text=update.message.text||"";if(text==="/start")return sendMessage(env,chatId,`👋 <b>${env.COMPANY_NAME||"KeyCRM"} Telegram Assistant</b>\n\nОберіть звіт:`,mainKeyboard());if(text==="/getreport"||text==="/report")try{return await sendReport(env,chatId,"yesterday");}catch(error){return sendMessage(env,chatId,`⚠️ Помилка формування звіту: ${error.message}`,mainKeyboard());}const custom=parseCustomRange(text);if(custom)try{return await sendReport(env,chatId,custom);}catch(error){return sendMessage(env,chatId,`⚠️ ${error.message}\n\nВведіть період ще раз, наприклад: <code>01.09.2026 - 30.09.2026</code>`,mainKeyboard());}return sendMessage(env,chatId,"Натисніть /start, щоб відкрити меню.",mainKeyboard());}
if(update.callback_query){const callback=update.callback_query,chatId=callback.message?.chat?.id,data=callback.data||"";try{await answerCallback(env,callback.id);}catch(e){}if(!chatId)return;
if(data==="settings_home")return sendMessage(env,chatId,"⚙️ <b>Налаштування звітів</b>\n\nОберіть, що потрібно налаштувати:",settingsHomeKeyboard());
if(data==="settings_statuses")try{return await showStatusSettings(env,chatId);}catch(error){return sendMessage(env,chatId,`⚠️ Помилка налаштувань: ${error.message}`,mainKeyboard());}
if(data==="settings_payments")try{return await showPaymentSettings(env,chatId);}catch(error){return sendMessage(env,chatId,`⚠️ Помилка налаштувань оплати: ${error.message}`,mainKeyboard());}
if(data.startsWith("settings_payment_")){const key=data.slice(17);try{await togglePaymentSetting(env,chatId,key);return await showPaymentSettings(env,chatId);}catch(error){return sendMessage(env,chatId,`⚠️ Не вдалося зберегти налаштування оплати: ${error.message}`,mainKeyboard());}}
if(data==="settings_back")return sendMessage(env,chatId,"Оберіть звіт:",mainKeyboard());
if(data.startsWith("settings_group_")){const groupKey=data.slice(15);try{return await showStatusGroup(env,chatId,groupKey);}catch(error){return sendMessage(env,chatId,`⚠️ Помилка налаштувань: ${error.message}`,mainKeyboard());}}
if(data.startsWith("settings_toggle_")){const rest=data.slice(16),separator=rest.indexOf("_"),groupKey=separator>=0?rest.slice(0,separator):"",statusId=separator>=0?rest.slice(separator+1):"";try{await toggleStatus(env,chatId,groupKey,statusId);return await showStatusGroup(env,chatId,groupKey);}catch(error){return sendMessage(env,chatId,`⚠️ Не вдалося зберегти статус: ${error.message}`,mainKeyboard());}}
if(data==="orders_custom")return sendMessage(env,chatId,"📆 <b>Довільний період</b>\n\nВведіть дві дати одним повідомленням.\nНаприклад: <code>01.09.2026 - 30.09.2026</code>",mainKeyboard());
if(data.startsWith("excel_")){try{return await sendExcel(env,chatId,decodePeriodKey(data.slice(6)));}catch(error){console.error("Excel export failed",error);return sendMessage(env,chatId,`⚠️ Помилка створення Excel: ${error.message}`,mainKeyboard());}}
if(data.startsWith("orders_")){const period=data.slice(7);try{return await sendReport(env,chatId,period);}catch(error){return sendMessage(env,chatId,`⚠️ Помилка формування звіту (${period}): ${error.message}`,mainKeyboard());}}
return sendMessage(env,chatId,`⚠️ Невідома команда кнопки: ${data}`,mainKeyboard());}}
export default {async fetch(request,env,ctx){const url=new URL(request.url);if(request.method==="GET"&&url.pathname==="/health")return Response.json({ok:true,service:"keycrm-telegram-assistant",version:"4.0.0",d1:Boolean(env.DB)});if(request.method==="GET"&&url.pathname==="/setup")return setupWebhook(request,env);if(request.method!=="POST"||url.pathname!=="/webhook")return new Response("Not found",{status:404});if(!validWebhook(request,env))return new Response("Unauthorized",{status:401});try{const update=await request.json();ctx.waitUntil(handleUpdate(update,env).catch(error=>console.error("handleUpdate failed",error)));return new Response("OK");}catch(error){return new Response("Bad request",{status:400});}},async scheduled(controller,env,ctx){ctx.waitUntil(syncOrderState(env).then(result=>console.log("Scheduled order-state sync",JSON.stringify({cron:controller.cron,...result}))).catch(error=>console.error("Scheduled order-state sync failed",error)));}};
